language: node_js
sudo: required
services:
  - docker

before_install:
#build docker before run this image
# tagname convention:gitId/ name of git repo(this tag will only be used in travisCI so nomatter what it's called just a good convention)
  - docker build -t frontend -f Dockerfile.dev .

script: 
  - docker run -e CI=true clara-lan/react-docker npm run test